  // File generated by FlutterFire CLI.
  // ignore_for_file: type=lint
  import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
  import 'package:flutter/foundation.dart'
      show defaultTargetPlatform, kIsWeb, TargetPlatform;

  /// Default [FirebaseOptions] for use with your Firebase apps.
  ///
  /// Example:
  /// ```dart
  /// import 'firebase_options.dart';
  /// // ...
  /// await Firebase.initializeApp(
  ///   options: DefaultFirebaseOptions.currentPlatform,
  /// );
  /// ```
  class DefaultFirebaseOptions {
    static FirebaseOptions get currentPlatform {
      if (kIsWeb) {
        return web;
      }
      switch (defaultTargetPlatform) {
        case TargetPlatform.android:
          throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for android - '
            'you can reconfigure this by running the FlutterFire CLI again.',
          );
        case TargetPlatform.iOS:
          throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for ios - '
            'you can reconfigure this by running the FlutterFire CLI again.',
          );
        case TargetPlatform.macOS:
          throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for macos - '
            'you can reconfigure this by running the FlutterFire CLI again.',
          );
        case TargetPlatform.windows:
          throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for windows - '
            'you can reconfigure this by running the FlutterFire CLI again.',
          );
        case TargetPlatform.linux:
          throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for linux - '
            'you can reconfigure this by running the FlutterFire CLI again.',
          );
        default:
          throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.',
          );
      }
    }

    static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyCU0I96O0uKLnrdVwYeZyBRsDtV3wayv9w',
      appId: '1:712873519787:web:8a9f05531da54e2064e5ee',
      messagingSenderId: '712873519787',
      projectId: 'battle-activity',
      authDomain: 'battle-activity.firebaseapp.com',
      storageBucket: 'battle-activity.firebasestorage.app',
      measurementId: 'G-GQBDS36CNM',
    );
  }
